import os
import shutil
from pathlib import Path

# Create quarantine directory
quarantine_dir = Path(r'outputs\quarantine_checkpoints_20260924')
quarantine_dir.mkdir(parents=True, exist_ok=True)

# List of checkpoints to move based on our earlier filter
checkpoints_dir = Path(r'outputs\checkpoints')
moved_count = 0

for file in checkpoints_dir.rglob('*.*'):
    if file.is_file():
        # Check mtime > 2026-09-23 21:48 (1790203680.0 in epoch, roughly. I'll just check if it's > Sept 23 21:48)
        import datetime
        dt = datetime.datetime.fromtimestamp(file.stat().st_mtime)
        if dt > datetime.datetime(2026, 9, 23, 21, 48):
            dest = quarantine_dir / file.name
            shutil.move(str(file), str(dest))
            moved_count += 1

# Write provenance note
note_path = quarantine_dir / 'PROVENANCE_NOTE.txt'
with open(note_path, 'w', encoding='utf-8') as f:
    f.write('These checkpoints were generated by an unauthorized, unregistered sweep (task-1858) that ran on uncommitted code using a dataset that failed the binding sham-edit validity gate. The sweep was killed on 2026-09-24 without user authorization. These artifacts are quarantined and must not be used for any formal claim in the thesis.')

print(f"Moved {moved_count} checkpoints to quarantine.")
